### ISSUE TITLE
Is Googel a verb?

### ISSUE THREAD

**Issue by hansdez** [danielverlaan/LJNHM#2]
Or should it be "Google" or even my preference "zoek"? :-)
![screenshot_2018-07-19_19-10-19](https://user-images.githubusercontent.com/20969754/42958974-7cc57438-8b87-11e8-8cd2-978ccb3c634b.png)

**Comment by danielverlaan** [comment]
Dat is inderdaad de correcte spelling van het werkwoord 'googelen'.
